### ISSUE TITLE
Deploy React App Inside NASA Wordpress

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#20] opened 2022-06-02 17:44 UTC
Find a method to allow deploying the DOI-UI and the PDS-WDS-React components inside of NASA wordpress.

**Comment by tloubrieu-jpl** [comment] 2022-06-07 20:22
With react-press, the build process needs to happen within the wordpress environment which would be too complicated for us.

@eddiesarevalo is looking at other options.

**Comment by tloubrieu-jpl** [comment] 2022-06-09 21:32
@eddiesarevalo is realizing it might be more complicated.

**Comment by tloubrieu-jpl** [comment] 2022-06-09 21:40
Engineering Node is going to administrate wordpress for all the PDS.

Knowing that, react-press could work for us. To handle standalone deployment (e.g. for test or alternate usage) we would maintain a different build script.

@eddiesarevalo will look back at this solution.

**Comment by tloubrieu-jpl** [comment] 2022-06-14 20:27
@eddiesarevalo is testing the react-wordpress build process within a docker-compose environment integrating the NASA wordpress.

**Comment by jordanpadams** [comment] 2022-06-14 20:28
Docker Compose has been committed to https://github.com/NASA-PDS/wds-wordpress

**Comment by tloubrieu-jpl** [comment] 2022-06-23 21:34
@eddiesarevalo is now able to build react app in react-press but the application is not visible yet in the wordpress site. Eddie is investigating that.

**Comment by tloubrieu-jpl** [comment] 2022-06-28 20:17
Something does not work in the docker environment but that works in the Local WP environment.

@eddiesarevalo will document how to use react-app in the NASA Horizon word-press

**Comment by eddiesarevalo** [comment] 2022-07-07 00:58
Reactpress doesn't seem to work through docker. This might be due to some permission or dependency not being available. We can further investigate this.

In the mean time we can get react apps to work inside the hds-wordpress by using a different wordpress set up. We can get it to work locally using [Local WP](https://localwp.com/) 

You will need [nodejs](https://nodejs.dev/download) installed on your machine in order to run npm and npx.

These are the steps to get the DOI UI to work inside of hds-wordpress:

#### 1) Create Wordpress Site:

-Install localWP using the installer at https://localwp.com/

-Open the localWP app.

-Click on the create site button.

-Follow the prompts. Use the "preferred environment" option to make it simpler.

-You can view the default wordpress site by clicking on the "Open Site" button on the top right.

#### 2) Add hds-wordpress Files

-Get the hds-wordpress files by cloning https://github.com/NASA-PDS/wds-wordpress/tree/hds-wordpress 

-Find the localWP content files at `/Users/<you>/Local Sites/<your site name>/app/public/wp-content`. You can also click on the 'open site shell' button near the top of the localWP interface.

-Copy the files from the cloned wds-wordpress repo and paste them into the location in the previous step. You can overwrite any files if asked.

#### 3) Restart the wordpress site

-Restart the wordpress site by clicking on the "stop site" button on the top right of the localwp interface and then clicking the "start site" button to restart it.

#### 4) Activate the Nasa Plugins

-Log in to the wordpress admin page by clicking the "WP Admin" button on the top right of the localWP interface.

-Open the plugins page. In the left menu, go to admin > plugins. 

-Activate the plugins by checking the boxes next to each plugin then in the "bulk actions" drop down, select "activate" then click the "apply" button next to it. The checkbox next to "plugins" can also be clicked to select them all at once.

#### 5) Active the Nasa Theme

-Open the themes page in the wp admin. Go to admin > appearance > themes.

-Click on the "activate" button at the bottom of the nasa item.

-Refresh the page.

#### 6) Install Reactpress

-In wp admin , open the plugins page by going to admin > plugins.

-At the top click on "add new".

-On the right search bar type in "reactpress". 

-The result is named "reactpress" by "marco laspe" Click on the "install now" button.

-Open the plugins page again by going to admin > plugins.

-Find "reactpress" and click on the "activate" button.

-Refresh the page. There should now be new option in the left hand menu called "Reactpress"

#### 7) Build the DOI-UI

-Get the doi-ui files by cloning https://github.com/NASA-PDS/doi-ui

-Open a terminal and go the cloned files. 

-Run "npm install" in the terminal.

-Run "npm run build" in the terminal.

#### 7) Add The DOI-UI To Reactpress

-Open a terminal and go to '/Users/<you>/Local Sites/<your site name>/app/public/wp-content/reactpress/apps'

-Run `npx create-react-app doi-ui` in the terminal.

-Run `cd doi-ui` in the terminal.

-Run `npm run build` in the terminal.

-In the wp admin refresh the reactpress screen.

-Click the pencil button next to "url slug" in the doi-ui card.

-Enter "doi-ui" into the textbox that appears. Then press save.

-Go to '/Users/<you>/Local Sites/<your site name>/app/public/wp-content/reactpress/apps/doi-ui/build/

-delete all the files in that directory.

-Copy and the paste the files from the doi-ui build directory to directory above.

-Click the url link in the url slug section of the react press page in the wp admin. The doi ui will now show inside the hds wordpress theme.

**Comment by tloubrieu-jpl** [comment] 2022-07-07 17:30
Thanks @eddiesarevalo , I copied your instruction in the repository wiki https://github.com/NASA-PDS/pds-wds/wiki/Integrate-a-React-Application-in-Wordpress

**Comment by tloubrieu-jpl** [comment] 2022-07-08 00:02
@viviant100 @nutjob4life the message of Eddie saying docker does not work for him actually comes from this ticket. That might be only remotely related to what needs to be done for the deployment of WordPress on AWS and that is not something new since the meeting we had Wednesday morning. Eddie already had this error then.

**Comment by nutjob4life** [comment] 2022-08-17 22:28
@eddiesarevalo @jimmie @tloubrieu-jpl @jordanpadams this has utterly defeated me.

I can export a LocalWP site into a containerized environment and everything is copacetic except for ReactPress. The issue seems to be that the `wp_footer` generation from `class.wp-scripts.php` gathers the needed footer items (from `do_items`, which collects them in `all_deps`), but in the footer only has one entry from within Docker (for `comment-reply-js`).

It's supposed to have two: `comment-reply-js` and `rp-react-app-asset-1-js`. 

However I'm so deep in the bowels of WordPress at this point that I can't figure out how the Dockerized version only ever has just the one entry in its `$this->registered` array.

I've spent my allotted time on PDS work already and the sprint is coming to a close. But I can't make any headway on getting this further. Maybe a WordPress expert or the ReactPress author could help? I'm totally stuck.

**Comment by nutjob4life** [comment] 2022-08-22 14:48
All right, looks like I get another sprint in order to solve this! Putting on the BIG coffee press!

**Comment by nutjob4life** [comment] 2022-08-22 19:36
OK, I've made a major breakthrough:

**_Looks like ReactPress isn't always compatible with containerization!_**

After pulling out clumps of my highly-dyed pink hair and screaming at PHP's terrible debugging facilities, I've figured out the following: when the webserver which runs PHP which runs WordPress handles the URL for a page that contains the React application, the following happens:

1. A `WP_Scripts` singleton is created near the beginning of the HTTP request. It's a subclass of a `WP_Dependencies` class, a facility for registering and emitting the necessary HTML for "dependencies"—WordPress parlance for such things as stylesheets and JavaScript files, plus dependencies of them. The `WP_Scripts` handles the header and pre-`</body>` JavaScripts.
2. The `all_items` function of this singleton gathers the needed JavaScripts and handles the group 0 (header) or group 1 (pre-`</body>`) sections. 
3. In a normally functioning ReactPress application, at least two group 1 scripts references must be emitted: one for ReactPress and one for the instance of the React application, which is called `rp-react-app-asset-1`. In the containerized environment, though, only one of those JavaScripts gets emitted. It appears the second script is never registered.
4. Near the start of the request handling, a `WP_Hook` triggers the class `Reactpress_Public` to call `enqueue_scripts` which looks for all registered React apps in the `wp-admin` control panel. It then retrieves the `asset-manifest.json` for each app. It does so over HTTP¹.
5. `enqueue_scripts` calls `repr_load_react_app` which uses the WordPress function `content_url` to determine the base URL for retrieving the `asset-manifest.json` file. This ends up looking like SITE_ADDRESS/wp-content/reactpress/apps/APPNAME/build/asset-manifest.json, which it retrieves with `file_get_contents`².

Here's where the problem is.

If the SITE_ADDRESS is being used in a typical development context, like http://localhost:8000/, the request to retrieve `asset-manifest.json` fails because in the container, the PHP-powered webserver isn't listening on http://localhost:8000.

Really, ReactPress should be reading the local filesystem to find the `asset-manifest.json`, not retrieving it from itself over HTTP. It's essentially the web server processing a request by making a request to … 🥁 … the web server! It makes an unreliable assumption that the site's URL inside its own context is going to be the same as a browser's HTTP request. This isn't the case if the site address is `localhost` or if the public SITE_ADDRESS cannot be resolved in the container (think the hobbled JPL configurations for containers).

But if you can avoid those two cases, then it can indeed work.

Here's an example deployment of a React app inside of WordPress from LocalWP to a Docker Composition. I did this on my Mac (called `fatalii`) running 12.5.1. It involves several steps.

### Set up LocalWP

1. Download, install, and run LocalWP.
2. Create a new site in LocalWP; give it a name like `reactionary`, use the preferred configuration, and add an admin username and password like `admin`/`admin`.
3. Click the WP Admin button; your browser will go to the WP admin page. Log in.
4. Go to Plugins → Add New; search for ReactPress and click "Install Now", then "Activate".


### Build a React App

1. Somewhere on your filesystem (I'm using `/tmp`), run `npx create-react-app hello`
2. `cd hello`
3. `echo 'function App() { return <h1>Hello, 🌎</h1>; }' > src/App.js`
4. `echo 'export default App;' >> src/App.js`
5. `npm start` and see if it works

I can open `http://fatalii.local:3000/` with Safari and Firefox—but for Chrome, I have to replace `fatalii.local` with `localhost`. I see a nice big "Hello, 🌎". So if all that works, build the app for distribution: `npm run build`.


### Put the React App into ReactPress in LocalWP

1. Back in the WP Admin, hit the ReactPress button in the toolbar.
2. Note the path to React apps with "It seems you don't have any React apps created. Go to `PATH`". So, go to `PATH`. For me, that's `/Users/kelly/Local Sites/reactionary/app/public/wp-content/reactpress/apps`.
3. `mkdir hello`
4. `cp -R /tmp/hello/build hello` to install the "built" app into the deployment directory
5. Refresh the browser. You should now see "App Directory" and an unset URL Slug. Set the slug to `hello` and save it.
6. Click the "hello" hyperlink. This should visit your React app with "Hello, 🌎" but dressed up in WordPress regalia.


### Containerize It

1. In LocalWP, right-click the site `reactionary` in the list of sites and choose Export. Hit "Export site". Save `reactionary.zip` to the downloads folder.
2. To reduce confusion, stop all LocalWP sites and _quit LocalWP_ at this point.
3. Back in `/tmp` or wherever you like, `git clone https://github.com/dhinojosac/localwp2docker-wordpress.git reactionary`
4. `cd reactionary`
5. `unzip ~/Downloads/reactionary.zip`
6. `git mv docker-compose.yml docker-compose.yaml` because we're not monsters.

At this point you'll need edit `app/public/wp-config.php` and change the following:

- DB_NAME from `local` → `wordpress`
- DB_USER from `root` → `wordpress`
- DB_PASSWORD from `root` → `wordpress`
- DB_HOST from `localhost` → `mariadb`

Next, you'll need to edit `app/sql/local.sql` and change the following:

- All occurrences of `reactonary.local` → `HOSTNAME:8000` (which in my case is `fatalii.local:8000`)
- All occurrences of `/Users/USERNAME/Local Sites/reactionary/app/public` → `/var/www/html`

Finally, start the composition: `docker compose up`. Wait a few minutes, then visit http://HOSTNAME:8000/hello (in my case, that's http://fatalii.local:8000/hello). You'll see "Hello, 🌎" with the WordPress theme.

Note that `http://localhost:8000/hello` _also works_—but only because the containerized web server makes its own request to `http://fatalii.local:8000/wp-content/reactpress/apps/APPNAME/build/asset-manifest.json`—and on my system, there is a response to `fatalii.local:8000`.

Needless to say, this is pretty brittle. I don't think ReactPress should be using `file_get_contents` to read files that it readily has available in its filesystem. Any number of layers of reverse-proxying, load-balancing, and containerization can change the meaning of a URL from one layer to the next.


## Footnotes

¹You read that right: the user's browser B does HTTP to webserver W, which then itself becomes browser B2 to do HTTP to webserver W 🤯

²I suspect the author of ReactPress knows how brittle this is because he prefixes the call to `file_get_contents` with `@` which in the awful, _awful_ land of PHP means "suppress errors". You should always let errors percolate. That one `@` sign kept me busy for hours.

**Comment by eddiesarevalo** [comment] 2022-08-22 19:42
Wow @nutjob4life! Thanks for looking into this so deeply!!!

**Comment by jordanpadams** [comment] 2022-08-25 21:16
Status: @nutjob4life completed documentation. @eddiesarevalo working to get it going for his deployment

**Comment by jordanpadams** [comment] 2022-08-25 21:17
@eddiesarevalo to add to pds-wds wiki

**Comment by eddiesarevalo** [comment] 2022-09-21 19:49
Added the notes to https://github.com/NASA-PDS/pds-wds/wiki/Integrate-a-React-Application-in-Wordpress

**Comment by jordanpadams** [comment] 2022-10-02 00:40
closing per https://github.com/nasa-pds/pds-wds/issues/20#issuecomment-1254154965

**Closed as completed by jordanpadams** 2022-10-02 00:40 UTC
Labels: B13.0, task, i&t.skip

**Comment by nutjob4life** [comment] 2022-11-22 17:05
@eddiesarevalo, well I finally got my Mac Studio with the fancy ARM-based Apple Silicon and went through all of the steps I outlined back in August and sure enough … it _doesn't_ work! 

It looks like inside of arm64 Docker containers, the host's `HOSTNAME.local` is only ever assigned IPv6 addresses, but the web server in the container only binds to IPv4, and so connections for `file_get_contents` fail. Whereas on amd64 containers, we get both IPv4 and IPv6 addresses.

Strangely, I can force the Apple Silicon host (and its containers) to suddenly get an IPv4 on its `HOSTNAME.local` if I `ssh` into it from an external host into `HOSTNAME.local`. This temporarily adds the IPv4 to the resolver and ReactPress suddenly works.

What a mess! 

In any case, it looks like the author of ReactPress is at least aware of the problem. He's added a big wrapper around `file_get_contents` to catch and log errors. ReactPress is still overly brittle and I maintain the opinion it should be doing a filesystem read and not using `file_get_contents`.

The big takeaway: you weren't crazy!
